write_register:
  name: Write Register
  description: Write a value to a specific register on a Heatmiser device
  target:
    device:
      integration: heatmiser_edge
  fields:
    register:
      name: Register
      description: The register address to write to (0 indexed)
      required: true
      selector:
        number:
          min: 50
          max: 217
          mode: box
    value:
      name: Value
      description: The value to write to the register
      required: true
      selector:
        number:
          min: 0
          max: 65535
          mode: box